version: 2.1

orbs:
  haskell: haskell-works/haskell-build-2@1.6.16
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@dev:araga

workflows:
  multiple-ghc-build:
    jobs:
      # - haskell/build:
      #     name: GHC 8.4.4
      #     executor: haskell/ghc-8_4_4
      #     context: haskell-ci

      # - haskell/build:
      #     name: GHC 8.6.5
      #     executor: haskell/ghc-8_6_5
      #     context: haskell-ci

      - hackage/upload:
          context: haskell-ci
          publish: false
          # filters:
          #   branches:
          #     only: master
